const errorCodesList = {
  "Provide either a idPartner or idUser"                                                    : "",
  "Cannot provide both idPartner and idUser"                                                : "",
  "The provided idUser or idPartner does not exist"                                         : "",
  "Invalid AddressType; main address is only added upon creation of Partner/User"           : "",
  "Unable to add new Address"                                                               : "",
  "New Address added successfully"                                                          : "",
  "idAddress is null or does not exist"                                                     : "",
  "Unable to delete Address"                                                                : "",
  "Address deleted successfully"                                                            : "",
  "p_idAddress is null or does not exist"                                                   : "",
  "Invalid idAddress"                                                                       : "",
  "No row was updated"                                                                      : "",
  "Update successful"                                                                       : "",
  "Invalid or expired key"                                                                  : "",
  "Verify error. Unable to identify user from key"                                          : "",
  "Key is valid"                                                                            : "",
  "BookingDateTimeFrom is an invalid datetime string"                                       : "",
  "BookingDateTimeTo is an invalid datetime string"                                         : "",
  "BookingPartner is null or does not exist"                                                : "",
  "BookingUser is null or does not exist"                                                   : "",
  "Invalid DateFrom and DateTo"                                                             : "",
  "Unable to add new Booking"                                                               : "",
  "New Booking added successfully"                                                          : "",
  "Bookingid is null or does not exist"                                                     : "",
  "Cannot update a Booking with this BookingStatus"                                         : "",
  "Invalid BookingFleetType"                                                                : "",
  "BookingFleetQty is null or zero or negative"                                             : "",
  "Unable to add new BookingFleet"                                                          : "",
  "New BookingFleet added successfully"                                                     : "",
  "idBookingFleet is null or does not exist"                                                : "",
  "Unable to delete BookingFleet"                                                           : "",
  "BookingFleet deleted successfully"                                                       : "",
  "BookingFleetQty cannot be zero or negative"                                              : "",
  "Unable to update BookingFleet"                                                           : "",
  "BookingFleet updated successfully"                                                       : "",
  "idBooking is null or does not exist"                                                     : "",
  "Must provide both BookingDateTimeFrom and BookingDateTimeTo or neither"                  : "",
  "Invalid BookingStatus"                                                                   : "",
  "Cannot request this booking"                                                             : "",
  "Cannot quote this booking"                                                               : "",
  "Cannot decline this booking"                                                             : "",
  "Cannot confirm this booking"                                                             : "",
  "Cannot delete this booking"                                                              : "",
  "Cannot accept this booking"                                                              : "",
  "Cannot update this booking"                                                              : "",
  "This booking is not marked for update"                                                   : "",
  "Partner name cannot be NULL"                                                             : "Please fill in partner company name",
  "Partner email cannot be NULL"                                                            : "Please fill in partner email",
  "Partner name already in use"                                                             : "Partner company name already used",
  "Partner email is invalid"                                                                : "Please enter a valid email address",
  "Partner email already in use"                                                            : "Partner email already used",
  "PartnerTnCFlag value must be 1, partner must agree to the T&C"                           : "Please agree to the Terms and Conditions",
  "UserFirstName cannot be null"                                                            : "Please enter your first name",
  "UserEmail is invalid"                                                                    : "Please enter a valid email address",
  "UserEmail already exists"                                                                : "This user email is taken",
  "UserPhoneNumber already exists"                                                          : "This user phone number is taken",
  "UserTnCFlag value must be 1, user must agree to the T&C"                                 : "Please agree to the Terms and Conditions",
  "Unable to add new User"                                                                  : "Please check data entered",
  "Invalid Login Name"                                                                      : "Invalid login name",
  "Invalid Login Password"                                                                  : "Invalid login password",
  "UserFirstName must be a valid string"                                                    : "Please enter your first name",
  "UserEmail must be a valid string"                                                        : "Please enter your email address",
  "UserEmail is not a valid email"                                                          : "Please enter a valid email address",
  "UserPhoneNumber must be a valid string"                                                  : "Please enter your phone number",
  "UserPassword must be a valid string"                                                     : "Please enter a password",
  "UserPhoneNumberCountryCode must be a valid string"                                       : "Please enter your country code",
  "UserTnCFlag must be 1 or 0"                                                              : "Please agree to the Terms and Conditions",
  "UserEmailSubscribeFlag must be 1 or 0"                                                   : "Please check the email subscription box",
  "Unable to register. Query failed."                                                       : "Please check data entered",
  "PartnerName must be a valid string"                                                      : "Please fill in partner company name",
  "PartnerUserEmail must be a valid string"                                                 : "Please fill in partner email",
  "PartnerUserEmail is not a valid email"                                                   : "Please enter a valid email address",
  "PartnerUserPassword must be a valid string"                                              : "Please enter a password",
  "PartnerUserFirstName must be a valid string"                                             : "Please enter your first name",
  "PartnerUserLastName must be a valid string"                                              : "Please enter your last name",
  "PartnerUserCountryCode must be a valid string"                                           : "Please enter your country code",
  "PartnerUserMobileNumber must be a valid string"                                          : "Please enter your mobile number",
  "PartnerTnCFlag must be 1 or 0"                                                           : "Please agree to the Terms and Conditions",
  "PartnerEmailSubscribeFlag must be 1 or 0"                                                : "Please check the email subscription box",
}

export default {
  translate: (errorCode) => {
    const _errorCode = errorCodesList[errorCode] || errorCode;
    return _errorCode;
  }
}